### ISSUE TITLE
Error: Instances of UndefinedObject are not indexable

### ISSUE THREAD

**Issue by a2bSuricate** [svenvc/NeoConsole#2]
I get an error (in p61 & p7) trying to load NeoConsole from github like:

Metacello new
   repository: 'github.com/svenvc/NeoConsole';
   baseline: 'NeoConsole';
   load.

Error: Instances of UndefinedObject are not indexable

This happens on fresh images loaded like:
wget -O- https://get.pharo.org/64/stable+vm | bash

I dont know if you (Sven) are just not finished moving from sthub to github or if I am doing something wrong...
loading from sthub still works.

**Comment by svenvc** [comment]
You made a typo, try
````
Metacello new
  repository: 'github://svenvc/NeoConsole/repository';
  baseline: 'NeoConsole';
  load.
````
Or
````
Metacello new
  repository: 'github://svenvc/NeoConsole/src';
  baseline: 'NeoConsole';
  load.
````

**Comment by a2bSuricate** [comment]
thank you! -> this works
I just didn't see the typo...
